title: "People - Department of Computer Engineering"
baseurl: "" # the subpath of your site, e.g. /blog
# baseurl: "/people.ce.pdn.ac.lk" # the subpath of your site, e.g. /blog

author:
  name: Department of Computer Engineering, UoP
  email:

description: ""

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Google Analytics Tracking (optional)
ga_tracking: G-RV3PFV0QLS
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

permalink: pretty
exclude:
  [
    "node_modules/",
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "package-lock.json",
    "script/",
    "LICENSE.txt",
    "lib/",
    "bin/",
    "README.md",
    "Rakefile",
    "graphic_templates",
    "*.py",
    "*.sh",
    "*.yml",
  ]

kramdown:
  syntax_highlighter_opts:
    block:
    line_numbers: false

# Guideline:https://www.digitalocean.com/community/tutorials/jekyll-compress-html0
compress_html:
  clippings: all
  comments: all
  endings: []
  startings: []
  blanklines: true
  profile: false
  # ignore:
  #   envs: all

timezone: Asia/Colombo
