name: Daily Updates

on:
  schedule:
    # # At 18:30 UTC on everyday (12.00 mid night in Sri Lanka)
    - cron: "30 18 * * *"

  # Enables a button on Actions tab
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update staff pages from portal
        run: |
          cd ./python_scripts
          python3 update_staff_pages.py
          cd ../

      - name: Update student profiles from Google Form
        env:
          GOOGLE_FORM_CSV_LINK: ${{ secrets.GOOGLE_FORM_CSV_LINK }}
        run: |
          cd ./python_scripts
          python3 update_profile_from_google_form.py
          cd ../

      - name: Update postgrad students from Google Form
        run: |
          cd ./python_scripts
          python3 update_postgrad_from_google_form.py
          cd ../

      - name: Resize student images
        run: |
          cd ./python_scripts
          python3 resize_student_images.py
          cd ../

      - name: Update Student Project Details
        run: |
          cd ./python_scripts
          python3 update_projects.py
          cd ../

      - name: Update Student/Staff Publication Details
        run: |
          cd ./python_scripts
          python3 update_publications.py
          cd ../

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          package-manager-cache: false

      - name: Format files
        run: |
          npm install --global prettier
          prettier --write "**/*.{js,json,md,yml,yaml,html,css,scss}" \
            --config .prettierrc.json \
            --ignore-path .prettierignore

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Daily Action update" || echo "No changes"
          git push
